// services/employeeService.js
const EMPLOYEES = [
  {
    id: 1,
    employeeCode: 'NV001',
    name: 'Nguyễn Thị Mai',
    title: 'Trưởng phòng Hành chính',
    position: 'Trưởng phòng',
    department: 'Hành chính Nhân sự',
    status: 'Biên chế',
    dob: '05/15/1995',
    gender: 'Nữ',
    address: '123 Đường Nguyễn Huệ, Quận 1, TP.HCM',
    phone: '0901234567',
    email: 'nguyenmaix@gmail.com',
    education: 'Cử nhân Kinh tế',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '02/03/2020',
    youthUnionMember: true,
    youthUnionDate: '01/05/2019',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/01/2020',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 2,
    employeeCode: 'NV002',
    name: 'Trần Văn Hùng',
    title: 'Chuyên viên IT',
    position: 'Chuyên viên IT',
    department: 'Công nghệ thông tin',
    status: 'Hợp đồng',
    dob: '10/12/1990',
    gender: 'Nam',
    address: '456 Đường Lê Lợi, Quận 3, TP.HCM',
    phone: '0909876543',
    email: 'tranhung@gmail.com',
    education: 'Cử nhân CNTT',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '01/01/2021',
    youthUnionMember: false,
    youthUnionDate: '01/02/2019',
    policyStatus: 'Thương binh',
    contractType: 'Hợp đồng',
    startDate: '15/02/2021',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Vợ và 2 con',
  },
  {
    id: 3,
    employeeCode: 'NV003',
    name: 'Lã Thị Lan',
    title: 'Kế toán trưởng',
    position: 'Kế toán trưởng',
    department: 'Tài chính Kế toán',
    status: 'Biên chế',
    dob: '03/20/1985',
    gender: 'Nữ',
    address: '789 Đường Nguyễn Trãi, Quận 5, TP.HCM',
    phone: '0905555555',
    email: 'lathilan@gmail.com',
    education: 'Thạc sĩ Kinh tế',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '10/10/2015',
    youthUnionMember: true,
    youthUnionDate: '05/05/2010',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '10/10/2019',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chồng và 1 con',
  },
  {
    id: 4,
    employeeCode: 'NV004',
    name: 'Phạm Khoa',
    title: 'Nhân viên Sales',
    position: 'Nhân viên Sales',
    department: 'Kinh doanh',
    status: 'Con liệt sĩ',
    dob: '08/18/1992',
    gender: 'Nam',
    address: '321 Đường Lý Thái Tổ, Quận 10, TP.HCM',
    phone: '0909999999',
    email: 'phamkhoa@gmail.com',
    education: 'Cử nhân Quản trị Kinh doanh',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '01/01/2019',
    youthUnionMember: true,
    youthUnionDate: '02/02/2018',
    policyStatus: 'Con liệt sĩ',
    contractType: 'Hợp đồng',
    startDate: '01/03/2022',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 5,
    employeeCode: 'NV005',
    name: 'Hoàng Thị Bích',
    title: 'Chuyên viên tuyển dụng',
    position: 'Chuyên viên tuyển dụng',
    department: 'Hành chính nhân sự',
    status: 'Biên chế',
    dob: '11/22/1990',
    gender: 'Nữ',
    address: '123 Đường Nguyễn Tất Thành, Quận 7, TP.HCM',
    phone: '0904444444',
    email: 'hoangbich@gmail.com',
    education: 'Cử nhân Nhân sự',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '11/11/2018',
    youthUnionMember: false,
    youthUnionDate: '01/01/2016',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '05/05/2018',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 6,
    employeeCode: 'NV006',
    name: 'Nguyễn Văn A',
    title: 'Nhân viên IT',
    position: 'Nhân viên',
    department: 'IT',
    status: 'Hợp đồng',
    dob: '02/25/1995',
    gender: 'Nam',
    address: '321 Đường Võ Thị Sáu, Quận 3, TP.HCM',
    phone: '0901112233',
    email: 'nguyenvana@gmail.com',
    education: 'Cử nhân CNTT',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '03/01/2020',
    youthUnionMember: true,
    youthUnionDate: '05/02/2019',
    policyStatus: 'Không',
    contractType: 'Hợp đồng',
    startDate: '01/01/2021',
    endDate: '01/01/2023',
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 7,
    employeeCode: 'NV007',
    name: 'Nguyễn Văn B',
    title: 'Nhân viên IT',
    position: 'Nhân viên',
    department: 'IT',
    status: 'Biên chế',
    dob: '07/12/1992',
    gender: 'Nam',
    address: '567 Đường Bến Nghé, Quận 1, TP.HCM',
    phone: '0904443322',
    email: 'nguyenbvn@gmail.com',
    education: 'Cử nhân CNTT',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '06/06/2017',
    youthUnionMember: false,
    youthUnionDate: '03/01/2018',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '15/06/2019',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 8,
    employeeCode: 'NV008',
    name: 'Lê Thị Hồng',
    title: 'Nhân viên Marketing',
    position: 'Nhân viên Marketing',
    department: 'Marketing',
    status: 'Biên chế',
    dob: '04/10/1993',
    gender: 'Nữ',
    address: '12 Đường Phan Đình Phùng, Quận Phú Nhuận, TP.HCM',
    phone: '0908887777',
    email: 'lehong@gmail.com',
    education: 'Cử nhân Marketing',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '05/05/2020',
    youthUnionMember: true,
    youthUnionDate: '03/03/2015',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/01/2026',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 9,
    employeeCode: 'NV009',
    name: 'Phan Văn Dũng',
    title: 'Chuyên viên Kinh doanh',
    position: 'Chuyên viên Kinh doanh',
    department: 'Kinh doanh',
    status: 'Hợp đồng',
    dob: '09/15/1988',
    gender: 'Nam',
    address: '34 Đường Nguyễn Tri Phương, Quận 5, TP.HCM',
    phone: '0903334444',
    email: 'phandung@gmail.com',
    education: 'Cử nhân Quản trị Kinh doanh',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '07/07/2019',
    youthUnionMember: true,
    youthUnionDate: '01/01/2017',
    policyStatus: 'Không',
    contractType: 'Hợp đồng',
    startDate: '01/02/2021',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  }, 
  {
    id: 10,
    employeeCode: 'NV010',
    name: 'Trần Thị Lan',
    title: 'Chuyên viên Hành chính',
    position: 'Chuyên viên',
    department: 'Hành chính Nhân sự',
    status: 'Biên chế',
    dob: '12/12/1994',
    gender: 'Nữ',
    address: '56 Đường Trần Hưng Đạo, Quận 1, TP.HCM',
    phone: '0907776666',
    email: 'tranthilan@gmail.com',
    education: 'Cử nhân Quản trị Nhân sự',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '01/06/2018',
    youthUnionMember: true,
    youthUnionDate: '01/01/2016',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/03/2020',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 11,
    employeeCode: 'NV011',
    name: 'Nguyễn Văn C',
    title: 'Nhân viên IT',
    position: 'Nhân viên',
    department: 'IT',
    status: 'Hợp đồng',
    dob: '05/05/1991',
    gender: 'Nam',
    address: '78 Đường Lê Lai, Quận 1, TP.HCM',
    phone: '0902221111',
    email: 'nguyenvanc@gmail.com',
    education: 'Cử nhân CNTT',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '02/02/2020',
    youthUnionMember: true,
    youthUnionDate: '01/01/2018',
    policyStatus: 'Không',
    contractType: 'Hợp đồng',
    startDate: '01/07/2021',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Vợ và 1 con',
  },
  {
    id: 12,
    employeeCode: 'NV012',
    name: 'Phạm Thị Hạnh',
    title: 'Nhân viên Marketing',
    position: 'Nhân viên',
    department: 'Marketing',
    status: 'Biên chế',
    dob: '08/08/1992',
    gender: 'Nữ',
    address: '90 Đường Nguyễn Hữu Cảnh, Quận Bình Thạnh, TP.HCM',
    phone: '0905556666',
    email: 'phamthihanh@gmail.com',
    education: 'Cử nhân Marketing',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '03/03/2019',
    youthUnionMember: true,
    youthUnionDate: '01/01/2017',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/05/2020',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 13,
    employeeCode: 'NV013',
    name: 'Lê Văn Tùng',
    title: 'Chuyên viên Kinh doanh',
    position: 'Chuyên viên',
    department: 'Kinh doanh',
    status: 'Hợp đồng',
    dob: '02/02/1989',
    gender: 'Nam',
    address: '123 Đường Điện Biên Phủ, Quận 3, TP.HCM',
    phone: '0903332222',
    email: 'levantung@gmail.com',
    education: 'Cử nhân Quản trị Kinh doanh',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '05/05/2018',
    youthUnionMember: true,
    youthUnionDate: '01/01/2016',
    policyStatus: 'Không',
    contractType: 'Hợp đồng',
    startDate: '01/01/2021',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 14,
    employeeCode: 'NV014',
    name: 'Hoàng Văn Quang',
    title: 'Nhân viên IT',
    position: 'Nhân viên',
    department: 'IT',
    status: 'Biên chế',
    dob: '11/11/1993',
    gender: 'Nam',
    address: '45 Đường Phạm Ngũ Lão, Quận 1, TP.HCM',
    phone: '0908889999',
    email: 'hoangvanquang@gmail.com',
    education: 'Cử nhân CNTT',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '07/07/2016',
    youthUnionMember: false,
    youthUnionDate: '01/01/2015',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/01/2020',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 15,
    employeeCode: 'NV015',
    name: 'Nguyễn Thị Hòa',
    title: 'Chuyên viên Tuyển dụng',
    position: 'Chuyên viên',
    department: 'Hành chính nhân sự',
    status: 'Biên chế',
    dob: '06/06/1990',
    gender: 'Nữ',
    address: '67 Đường Nguyễn Văn Trỗi, Quận Phú Nhuận, TP.HCM',
    phone: '0907778888',
    email: 'nguyenthihoa@gmail.com',
    education: 'Cử nhân Nhân sự',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '05/05/2017',
    youthUnionMember: true,
    youthUnionDate: '01/01/2015',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/08/2019',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 16,
    employeeCode: 'NV016',
    name: 'Trần Văn Minh',
    title: 'Chuyên viên Kinh doanh',
    position: 'Chuyên viên',
    department: 'Kinh doanh',
    status: 'Hợp đồng',
    dob: '10/10/1987',
    gender: 'Nam',
    address: '89 Đường Cách Mạng Tháng 8, Quận 3, TP.HCM',
    phone: '0909991111',
    email: 'tranvanminh@gmail.com',
    education: 'Cử nhân Quản trị Kinh doanh',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '06/06/2019',
    youthUnionMember: true,
    youthUnionDate: '01/01/2016',
    policyStatus: 'Không',
    contractType: 'Hợp đồng',
    startDate: '01/02/2022',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Vợ và 1 con',
  },
  {
    id: 17,
    employeeCode: 'NV017',
    name: 'Lê Thị Mỹ Linh',
    title: 'Nhân viên Marketing',
    position: 'Nhân viên',
    department: 'Marketing',
    status: 'Biên chế',
    dob: '09/09/1992',
    gender: 'Nữ',
    address: '23 Đường Võ Văn Tần, Quận 3, TP.HCM',
    phone: '0904445555',
    email: 'lethimylinh@gmail.com',
    education: 'Cử nhân Marketing',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '01/01/2020',
    youthUnionMember: true,
    youthUnionDate: '01/01/2018',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/01/2026',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 18,
    employeeCode: 'NV018',
    name: 'Phạm Văn Nam',
    title: 'Nhân viên Sales',
    position: 'Nhân viên',
    department: 'Kinh doanh',
    status: 'Hợp đồng',
    dob: '03/03/1990',
    gender: 'Nam',
    address: '78 Đường Lý Tự Trọng, Quận 1, TP.HCM',
    phone: '0902223333',
    email: 'phamvannam@gmail.com',
    education: 'Cử nhân Quản trị Kinh doanh',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '01/01/2018',
    youthUnionMember: true,
    youthUnionDate: '01/01/2016',
    policyStatus: 'Không',
    contractType: 'Hợp đồng',
    startDate: '01/05/2021',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 19,
    employeeCode: 'NV019',
    name: 'Đặng Thị Phương',
    title: 'Chuyên viên Hành chính',
    position: 'Chuyên viên',
    department: 'Hành chính Nhân sự',
    status: 'Biên chế',
    dob: '07/07/1991',
    gender: 'Nữ',
    address: '34 Đường Nguyễn Hữu Thọ, Quận 7, TP.HCM',
    phone: '0906667777',
    email: 'dangthiphuong@gmail.com',
    education: 'Cử nhân Quản trị Nhân sự',
    politicalStatus: 'Đảng viên',
    politicalPartyDate: '05/05/2017',
    youthUnionMember: true,
    youthUnionDate: '01/01/2015',
    policyStatus: 'Không',
    contractType: 'Biên chế',
    startDate: '01/03/2019',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
  {
    id: 20,
    employeeCode: 'NV020',
    name: 'Nguyễn Văn Hậu',
    title: 'Nhân viên IT',
    position: 'Nhân viên',
    department: 'IT',
    status: 'Hợp đồng',
    dob: '01/01/1995',
    gender: 'Nam',
    address: '56 Đường Trần Phú, Quận 5, TP.HCM',
    phone: '0901114444',
    email: 'nguyenvanhau@gmail.com',
    education: 'Cử nhân CNTT',
    politicalStatus: 'Nhân sự trong Đoàn TNCS',
    politicalPartyDate: '01/01/2020',
    youthUnionMember: true,
    youthUnionDate: '01/01/2018',
    policyStatus: 'Không',
    contractType: 'Hợp đồng',
    startDate: '05/01/2026',
    endDate: null,
    workStatus: 'Đang làm việc',
    familyInfo: 'Chưa có thông tin gia đình',
  },
];

export const getEmployees = async () => {
  return Promise.resolve(EMPLOYEES);
};

export const getEmployeeById = async (id) => {
  const employee = EMPLOYEES.find(e => e.id === Number(id));
  return Promise.resolve(employee || null);
};
// services/dashboardService.js
export async function getDashboardStats() {
  // 🔁 thay URL này bằng API thật của bạn
  const res = await fetch("http://localhost:3000/api/dashboard/stats");

  if (!res.ok) {
    throw new Error("Không thể tải dữ liệu dashboard");
  }

  return res.json();
}
